server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gym?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.wjf.entity



